### ISSUE TITLE
 done is not defined

### ISSUE THREAD

**Issue by chrissyast** [JohnByrneRepo/mddir#12]
### System info 
MacOS 10.15.1

### What I've done

- `npm install mddir -g`
- `cd` to folder I want to view
- `mddir`

### Result
```
/usr/local/lib/node_modules/mddir/src/mddir.js:25
    if (err) return done(err);
             ^

ReferenceError: done is not defined
    at /usr/local/lib/node_modules/mddir/src/mddir.js:25:14
    at FSReqCallback.oncomplete (fs.js:146:23)
```

Followed [this](https://github.com/JohnByrneRepo/mddir/issues/7#issuecomment-340137044), still get the same

**Comment by angelod1as** [comment]
This is an error that shows when you throw an invalid folder. Try `mddir .` to see what happens. Is there any file or folder inside root?
